# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
#- script: echo "Hello World"
- script: | 
          7z a -tzip backup.zip *
          ls -lha  
          pwd 
#- script: azcopy login       
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure - Diogo(1)(8ea3853a-f6fe-4294-9479-14f58098f7f1)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: "azcopy copy '/home/vsts/work/1/s/backup.zip' 'https://diogoterraformtest.blob.core.windows.net/backup-git?sp=racwdl&st=2022-10-13T19:04:40Z&se=2022-10-14T03:04:40Z&spr=https&sv=2021-06-08&sr=c&sig=qkHAAV3CJXxtRJnhQirt3BHDpLVpvoSzbTNtZAOscQE%3D'"
    failOnStandardError: true
          

# task: AzureFileCopy@5
 # inputs:
 #   SourcePath: '*.*'
 #   azureSubscription: 'Azure - Diogo(8ea3853a-f6fe-4294-9479-14f58098f7f1)'
 #   Destination: 'AzureBlob'
 #   storage: 'diogoterraformtest'
 #   ContainerName: 'backup-git'
 #   BlobPrefix: 'backup'
  

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

