# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: linux-22.04

steps:
#- script: echo "Hello World"
- script: | 
          7z a -tzip backup.zip *
          ls -lha  
          pwd 
#- script: azcopy login       
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure - Diogo(1)(8ea3853a-f6fe-4294-9479-14f58098f7f1)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'azcopy copy backup.zip “https://diogoterraformtest.core.windows.net/backup-git”'
    failOnStandardError: true
          

# task: AzureFileCopy@5
 # inputs:
 #   SourcePath: '*.*'
 #   azureSubscription: 'Azure - Diogo(8ea3853a-f6fe-4294-9479-14f58098f7f1)'
 #   Destination: 'AzureBlob'
 #   storage: 'diogoterraformtest'
 #   ContainerName: 'backup-git'
 #   BlobPrefix: 'backup'
  

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

